version: '3.8'

services:
  app:
    build: .
    user: "1000:1000"  # Run as the host user to avoid permission issues
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./uploads:/app/uploads
      - ./downloads:/app/downloads
      - ./processed:/app/processed
      - ./temp:/app/temp
      - ./overlays:/app/overlays
      - ./credentials:/app/credentials
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    read_only: false

